#!/bin/bash

if [ "$EUID" -eq 0 ]
then
        echo -e "Do not run the script as root!\nScript stopped!"
        exit
fi

# Functions that add the custom configs
### conky
AddConky()
{
	sudo rm /etc/conky/conky.conf
	sudo cp ../configs/conky/conky.conf /etc/conky/
}
### bash
AddBash()
{
	cp -r ../configs/bash/. ~/
	#source ~/.bashrc  #Need to make this work!!
	echo "Hi from bash"
}
### sway
AddSway()
{
	echo "Hi from sway"
	mkdir -p ~/.config/sway
	cp -r ../configs/sway/. ~/.config/sway/
	swaymsg reload
}
### waybar
AddWaybar()
{
	echo "Hi from waybar"
	mkdir -p ~/.config/waybar
	cp -r ../configs/waybar/. ~/.config/waybar/
	swaymsg reload
}

if [ "$1" == "--update-all" ]; then
	AddConky
	AddSway
	AddWaybar
elif [ "$1" == "--update" ]; then
	"Add"$2
fi
